[project]
name = "_rs_sampler"
version = "0.1.0"
requires-python = ">=3.9"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "_rs_sampler"
bindings = "pyo3"
features = ["pyo3/extension-module"]
manifest-path = "Cargo.toml"
